name: Build and Upload Wheels

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Maturin
        run: |
          pip install maturin==1.8.3

      - name: Build wheels
        run: |
          maturin build --release --manylinux -i ${{ matrix.python-version }}

      - name: Upload to PyPI
        run: |
          maturin upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} --skip-existing target/wheels/*